#!/usr/bin/env python3
# (c) Chiel Kooijman 2014
from dice2 import roll, E, min_val, max_val, DiceExpression


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description='Roll some dice')
    parser.add_argument('expression', type=str, nargs='+',
                        help='Expression (e.g. 3d6+3)')
    parser.add_argument("-v", "--verbosity", action="count",
                        help="Print individual dice and constants")
    parser.add_argument("-e", "--expectancy", action="store_true",
                        help="Print expectancy instead of roll")
    parser.add_argument("--min", action="store_true",
                        help="Print minimum outcome")
    parser.add_argument("--max", action="store_true",
                        help="Print maximum outcome")
    args = parser.parse_args()
    if not args.verbosity:
        args.verbosity = 0

    dice_expression = DiceExpression("".join(args.expression))
    total = roll(dice_expression)
    exp = E(dice_expression)
    min = min_val(dice_expression)
    max = max_val(dice_expression)

    # Output
    if args.verbosity < 1:
        if args.expectancy:
            print(exp, end="")
        elif args.min:
            print(min, end="")
        elif args.max:
            print(max, end="")
        else:
            print(total, end=" ")
    else:
        print(total, end=" ")
        if args.verbosity and args.verbosity > 0:  # Print expectancy
            print("\t(exp: {}, min: {}, max: {}".format(exp, min, max),
                  end=")")
    print()
