.TH "DNDMAKE" "1" "March 2016" "dndmake 0.1" "User Commands"
.SH NAME
dndmake \- Generate a character
.SH SYNOPSIS
.B dndmake
[\fB\-h\fR]
[\fB\-m\fR|\fB\-f\fR]
[\fB\-t\fR|\fB\-s\fR]
[\fB\-b\fR|\fB\-l\fR]
[\fB\-n\fR \fINAME\fR]
{halfling,gnome,half-orc,elf,dwarf,human,half-elf}
[{CE,CN,LE,LN,NE,CG,NN,LG,NG}]
.SH DESCRIPTION
.PP
Generate a D&D character with a gender and a height and weight based on the
gender. Furthermore they have a hair and eye colour and a personality based on
the five-factor model (FFM), which influences their alignment. Gender, height,
weight and alignment can also be influenced or forced through arguments.
.SH OPTIONS
.TP
{halfling,gnome,half\-orc,elf,dwarf,human,half\-elf}
Race
.TP
{NN,LG,CE,CG,NE,CN,LN,LE,NG}
Alignment
.TP
.BR \-h ", " \-\-help
show this help message and exit
.TP
.BR \-m ", " \-\-male
Make a male character
.TP
.BR \-f ", " \-\-female
Make a female character
.TP
.BR \-t ", " \-\-tall
Make a tall character
.TP
.BR \-s ", " \-\-short
Make a short character
.TP
.BR \-b ", " \-\-heavy
Make a heavy character
.TP
.BR \-l ", " \-\-light
Make a light character
.TP
.BR \-n ", " \-\-name =\fINAME\fR
Character name
.\"usage: dndmake
.\"
.\"
.\"positional arguments:
.\"
.\"optional arguments:
