.TH "DNDMAKE" "1" "March 2016" "dndmake 0.2" "User Commands"
.SH NAME
dndmake \- Helper tool for D&D sessions
.SH SYNOPSIS
.B dndmake npc
[\fB\-h\fR]
[\fB\-v\fR]
{init,npc,wildshape (wi)}
.SH DESCRIPTION
.PP
Dndmake is a tool for managing D&D 3.5 campaigns.

It can generate NPCs, wildshapes, or help organise a campaign.

.SH OPTIONS
.TP
.BR \-h ", " \-\-help
show this help message and exit
.TP
.BR \-v ", " \-\-version
print version and exit
.PP

.SH DNDMAKE COMMANDS
{init,npc,wildshape}
.TP
.BR dndmake-init "(1)"
create a D&D campaign in the current directory.
.TP
.BR dndmake-npc "(1)"
generate a D&D character with a gender and a height and weight appearance and
personality
.TP
.BR dndmake-wildshape "(1)"
scrape an online character sheet and apply all animal templates for wildshape
stats
.TP
